In [24]:
import numpy as np
import math


# конвертация градусов в радианы
degree = 90
radian = math.radians(degree)
print(f'Конвертация радиан в градусы и обратно\nС помощью библиотеки math:\n{degree} градусов = {radian} радиан')

# конвертация радиан в градусы
radian = math.pi
degree = math.degrees(radian)
print(f'{radian} радиан = {degree} градусов')

# способ "вручную"
degree = 45
radian = degree/180*math.pi
print(f'Вручную:\n{degree} градусов = {radian} радиан')
radian = 1
degree = radian*180/math.pi
print(f'{radian} радиан = {degree} градусов')


# работа с библиотекой numpy
# примеры создания массивов
array1 = np.array([1, 34, 5.8, 92, -10])
array2 = np.array([[-3, 65, 87.5],[43, -59, 56.4]]) 
array3 = np.zeros((2,4))
array4 = np.ones((3,5))
array5 = np.eye(4)
array6 = np.empty((3,4))
array7 = np.arange(10,31,5)
print(f'\nПримеры создания массивов\nОдномерный массив \n{array1}')
print(f'Двумерный массив \n{array2}')
print(f'Использование функции zeros\n{array3}')
print(f'Использование функции ones\n{array4}')
print(f'Использование функции eye\n{array5}')
print(f'Использование функции empty\n{array6}')
print(f'Использование функции arange\n{array7}')

# демонстрация атрибутов
print(f'\nВывод формы и типа данных для двумерного массива\n{array2.shape}\n{type(array2)}')

# примеры индексирования и срезов
print(f'\nПолучение отдельного элемента\n{array6[1,2]}')
print(f'Извлечение подмассива с помощью среза\n{array6[[1,2]]}')
# примеры векторных операция и базовых статистик
print(f'\nПоэлементное сложение и умножение массивов\n{array1+array7}\n\n{array1*array7}')
print(f'Вычисление суммы элементов массива, средней величины, максимального элемента массива\n{np.sum(array2)}, {np.mean(array6)}, {array1.max()} ')


Конвертация радиан в градусы и обратно
С помощью библиотеки math:
90 градусов = 1.5707963267948966 радиан
3.141592653589793 радиан = 180.0 градусов
Вручную:
45 градусов = 0.7853981633974483 радиан
1 радиан = 57.29577951308232 градусов

Примеры создания массивов
Одномерный массив 
[  1.   34.    5.8  92.  -10. ]
Двумерный массив 
[[ -3.   65.   87.5]
 [ 43.  -59.   56.4]]
Использование функции zeros
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Использование функции ones
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Использование функции eye
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Использование функции empty
[[2.20005811e-307 2.80644109e-032 1.35441148e-306 2.87821559e+180]
 [0.00000000e+000 0.00000000e+000 1.03977794e-312 2.19996301e-307]
 [1.12208112e-047 1.09777553e-071 7.25488181e+169 8.22376426e-315]]
Использование функции arange
[10 15 20 25 30]

Вывод формы и типа данных для двумерного массива
(2, 3)
<class 'numpy.ndarray'>

Получение отдельного элемента
1.03977793